- id: 1
  title: Adventures of Huckleberry Finn
  author: Mark Twain
  text: "YOU don't know about me without you have read a book by the name of The Adventures of Tom Sawyer; but that ain't no matter.  That book was made by Mr. Mark Twain, and he told the truth, mainly.  There was things which he stretched, but mainly he told the truth.  That is nothing.  I never seen anybody but lied one time or another, without it was Aunt Polly, or the widow, or maybe Mary.  Aunt Polly Tom's Aunt Polly, she is and Mary, and the Widow Douglas is all told about in that book, which is mostly a true book, with some stretchers, as I said before."
- id: 2
  title: Pride and Prejudice
  author: Jane Austen
  text: "It is a truth universally acknowledged, that a single man in possession
of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered the rightful property of some one or other of their daughters."
- id: 3
  title: The Adventures of Sherlock Holmes
  author: Arthur Conan Doyle
  text: "To Sherlock Holmes she is always THE woman. I have seldom heard
him mention her under any other name. In his eyes she eclipses
and predominates the whole of her sex. It was not that he felt
any emotion akin to love for Irene Adler. All emotions, and that
one particularly, were abhorrent to his cold, precise but
admirably balanced mind. He was, I take it, the most perfect
reasoning and observing machine that the world has seen, but as a
lover he would have placed himself in a false position. He never
spoke of the softer passions, save with a gibe and a sneer. They
were admirable things for the observer--excellent for drawing the
veil from men's motives and actions. But for the trained reasoner
to admit such intrusions into his own delicate and finely
adjusted temperament was to introduce a distracting factor which
might throw a doubt upon all his mental results. Grit in a
sensitive instrument, or a crack in one of his own high-power
lenses, would not be more disturbing than a strong emotion in a
nature such as his. And yet there was but one woman to him, and
that woman was the late Irene Adler, of dubious and questionable
memory."
- id: 4
  title: Les Miserables
  author: Victor Hugo
  text: "In 1815, M. Charles-Francois-Bienvenu Myriel was Bishop of D---- He was
an old man of about seventy-five years of age; he had occupied the see
of D---- since 1806.

Although this detail has no connection whatever with the real substance
of what we are about to relate, it will not be superfluous, if merely
for the sake of exactness in all points, to mention here the various
rumors and remarks which had been in circulation about him from the very
moment when he arrived in the diocese. True or false, that which is said
of men often occupies as important a place in their lives, and above all
in their destinies, as that which they do. M. Myriel was the son of a
councillor of the Parliament of Aix; hence he belonged to the nobility
of the bar. It was said that his father, destining him to be the heir of
his own post, had married him at a very early age, eighteen or twenty,
in accordance with a custom which is rather widely prevalent in
parliamentary families. In spite of this marriage, however, it was said
that Charles Myriel created a great deal of talk. He was well formed,
though rather short in stature, elegant, graceful, intelligent; the
whole of the first portion of his life had been devoted to the world and
to gallantry."
- id: 5
  title: "Alice's Adventures in Wonderland"
  author: Lewis Carroll
  text: "Alice was beginning to get very tired of sitting by her sister on the
bank, and of having nothing to do: once or twice she had peeped into the
book her sister was reading, but it had no pictures or conversations in
it, 'and what is the use of a book,' thought Alice 'without pictures or
conversation?'

So she was considering in her own mind (as well as she could, for the
hot day made her feel very sleepy and stupid), whether the pleasure
of making a daisy-chain would be worth the trouble of getting up and
picking the daisies, when suddenly a White Rabbit with pink eyes ran
close by her."
- id: 6
  title: Grimms' Fairy Tales
  author: Jacob Grimm and Wilhelm Grimm
  text: "A certain king had a beautiful garden, and in the garden stood a tree
which bore golden apples. These apples were always counted, and about
the time when they began to grow ripe it was found that every night one
of them was gone. The king became very angry at this, and ordered the
gardener to keep watch all night under the tree. The gardener set his
eldest son to watch; but about twelve o'clock he fell asleep, and in
the morning another of the apples was missing. Then the second son was
ordered to watch; and at midnight he too fell asleep, and in the morning
another apple was gone. Then the third son offered to keep watch; but
the gardener at first would not let him, for fear some harm should come
to him: however, at last he consented, and the young man laid himself
under the tree to watch. As the clock struck twelve he heard a rustling
noise in the air, and a bird came flying that was of pure gold; and as
it was snapping at one of the apples with its beak, the gardener's son
jumped up and shot an arrow at it. But the arrow did the bird no harm;
only it dropped a golden feather from its tail, and then flew away.
The golden feather was brought to the king in the morning, and all the
council was called together. Everyone agreed that it was worth more than
all the wealth of the kingdom: but the king said, 'One feather is of no
use to me, I must have the whole bird.'"
- id: 7
  title: The Prince
  author: Niccolò Machiavelli
  text: "All states, all powers, that have held and hold rule over men have been
and are either republics or principalities.

Principalities are either hereditary, in which the family has been long
established; or they are new.

The new are either entirely new, as was Milan to Francesco Sforza, or
they are, as it were, members annexed to the hereditary state of the
prince who has acquired them, as was the kingdom of Naples to that of
the King of Spain."
- id: 8
  title: Metamorphosis
  author: Franz Kafka
  text: "One morning, when Gregor Samsa woke from troubled dreams, he found
himself transformed in his bed into a horrible vermin.  He lay on
his armour-like back, and if he lifted his head a little he could
see his brown belly, slightly domed and divided by arches into stiff
sections.  The bedding was hardly able to cover it and seemed ready
to slide off any moment.  His many legs, pitifully thin compared
with the size of the rest of him, waved about helplessly as he
looked."
- id: 9
  title: Moby Dick; Or, The Whale
  author: Herman Melville
  text: "Call me Ishmael. Some years ago--never mind how long precisely--having
little or no money in my purse, and nothing particular to interest me on
shore, I thought I would sail about a little and see the watery part of
the world. It is a way I have of driving off the spleen and regulating
the circulation. Whenever I find myself growing grim about the mouth;
whenever it is a damp, drizzly November in my soul; whenever I find
myself involuntarily pausing before coffin warehouses, and bringing up
the rear of every funeral I meet; and especially whenever my hypos get
such an upper hand of me, that it requires a strong moral principle to
prevent me from deliberately stepping into the street, and methodically
knocking people's hats off--then, I account it high time to get to sea
as soon as I can. This is my substitute for pistol and ball. With a
philosophical flourish Cato throws himself upon his sword; I quietly
take to the ship. There is nothing surprising in this. If they but knew
it, almost all men in their degree, some time or other, cherish very
nearly the same feelings towards the ocean with me."